### ISSUE TITLE
The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.

### ISSUE THREAD

**Issue by drfenixlinghu** [christian-byrne/audio-separation-nodes-comfyui#10]
log:

The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.

# ComfyUI Error Report
## Error Details
- **Node Type:** AudioSeparation
- **Exception Type:** ValueError
- **Exception Message:** The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.
## Stack Trace
```
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes\src\separation.py", line 83, in main
    sources = self.separate_sources(

  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes\src\separation.py", line 157, in separate_sources
    out = model.forward(chunk)

  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\python\lib\site-packages\torchaudio\models\_hdemucs.py", line 539, in forward
    raise ValueError(

```
## System Information
- **ComfyUI Version:** v0.2.7
- **Arguments:** E:\1-Stable-Diffusion\1-ComfyUI-Aki\main.py --auto-launch --preview-method auto --disable-cuda-malloc --fast
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 23588871168
  - **Torch VRAM Total:** 369098752
  - **Torch VRAM Free:** 27368448

## Logs
```
2024-11-12 15:58:59,164 - root - INFO - Total VRAM 24564 MB, total RAM 130569 MB
2024-11-12 15:58:59,164 - root - INFO - pytorch version: 2.5.1+cu124
2024-11-12 15:59:01,006 - root - INFO - xformers version: 0.0.28.post3
2024-11-12 15:59:01,007 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-12 15:59:01,007 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-11-12 15:59:01,238 - root - INFO - Using xformers cross attention
2024-11-12 15:59:02,196 - root - INFO - [Prompt Server] web root: E:\1-Stable-Diffusion\1-ComfyUI-Aki\web
2024-11-12 15:59:03,482 - root - WARNING - Traceback (most recent call last):
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\1-Stable-Diffusion\\1-ComfyUI-Aki\\custom_nodes\\ComfyUI-3D-MeshTool\\__init__.py'

2024-11-12 15:59:03,482 - root - WARNING - Cannot import E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-3D-MeshTool module for custom nodes: [Errno 2] No such file or directory: 'E:\\1-Stable-Diffusion\\1-ComfyUI-Aki\\custom_nodes\\ComfyUI-3D-MeshTool\\__init__.py'
2024-11-12 15:59:06,334 - numexpr.utils - INFO - Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-11-12 15:59:06,334 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2024-11-12 15:59:06,983 - datasets - INFO - PyTorch version 2.5.0+cu124 available.
2024-11-12 15:59:06,984 - datasets - INFO - TensorFlow version 2.12.0 available.
2024-11-12 15:59:07,290 - ComfyUI-CogVideoXWrapper.custom_cogvideox_transformer_3d - INFO - sageattn not found, using sdpa
2024-11-12 15:59:07,305 - ComfyUI-CogVideoXWrapper.cogvideox_fun.transformer_3d - INFO - sageattn not found, using sdpa
2024-11-12 15:59:07,306 - ComfyUI-CogVideoXWrapper.cogvideox_fun.fun_pab_transformer_3d - INFO - sageattn not found, using sdpa
2024-11-12 15:59:09,960 - root - INFO - Total VRAM 24564 MB, total RAM 130569 MB
2024-11-12 15:59:09,960 - root - INFO - pytorch version: 2.5.1+cu124
2024-11-12 15:59:09,960 - root - INFO - xformers version: 0.0.28.post3
2024-11-12 15:59:09,960 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-12 15:59:09,960 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-11-12 15:59:22,007 - root - INFO - 
Import times for custom nodes:
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\websocket_image_save.py
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ControlNet-LLLite-ComfyUI
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\FreeU_Advanced
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_TiledKSampler
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\stability-ComfyUI-nodes
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-WD14-Tagger
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_experiments
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\PowerNoiseSuite
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\images-grid-comfy-plugin
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_FizzNodes
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-Custom-Scripts
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-Frame-Interpolation
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\rgthree-comfy
2024-11-12 15:59:22,007 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-12 15:59:22,008 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\efficiency-nodes-comfyui
2024-11-12 15:59:22,008 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-Marigold
2024-11-12 15:59:22,008 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-LivePortraitKJ
2024-11-12 15:59:22,008 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_essentials
2024-11-12 15:59:22,008 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-UVR5
2024-11-12 15:59:22,008 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\comfyui-ollama
2024-11-12 15:59:22,008 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-12 15:59:22,008 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\comfyui-workspace-manager
2024-11-12 15:59:22,008 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-KJNodes
2024-11-12 15:59:22,008 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-12 15:59:22,008 - root - INFO -    0.0 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\comfyui_controlnet_aux
2024-11-12 15:59:22,008 - root - INFO -    0.1 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-Inspire-Pack
2024-11-12 15:59:22,008 - root - INFO -    0.1 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-Crystools
2024-11-12 15:59:22,008 - root - INFO -    0.2 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes
2024-11-12 15:59:22,008 - root - INFO -    0.6 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-12 15:59:22,008 - root - INFO -    0.6 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_EchoMimic
2024-11-12 15:59:22,008 - root - INFO -    0.6 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-Easy-Use
2024-11-12 15:59:22,008 - root - INFO -    0.6 seconds (IMPORT FAILED): E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-3D-MeshTool
2024-11-12 15:59:22,008 - root - INFO -    0.7 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-Manager
2024-11-12 15:59:22,008 - root - INFO -    1.9 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-Impact-Pack
2024-11-12 15:59:22,008 - root - INFO -    3.8 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI-CogVideoXWrapper
2024-11-12 15:59:22,008 - root - INFO -    4.2 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-12 15:59:22,008 - root - INFO -    5.5 seconds: E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_MaskGCT
2024-11-12 15:59:22,008 - root - INFO - 
2024-11-12 15:59:22,025 - root - INFO - Starting server

2024-11-12 15:59:22,025 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-12 16:00:58,525 - root - INFO - got prompt
2024-11-12 16:00:58,532 - root - WARNING - WARNING: 'NoneType' object has no attribute 'endswith'
2024-11-12 16:00:58,532 - root - WARNING - WARNING: 'NoneType' object has no attribute 'endswith'
2024-11-12 16:01:16,794 - ComfyUI-UVR5.uvr5.vr - INFO - 291c04e5db01b9d20e13eee56da15c8e.mp3.reformatted.wav instruments done
2024-11-12 16:01:16,904 - ComfyUI-UVR5.uvr5.vr - INFO - 291c04e5db01b9d20e13eee56da15c8e.mp3.reformatted.wav vocals done
2024-11-12 16:01:16,923 - root - INFO - Prompt executed in 18.40 seconds
2024-11-12 16:10:51,144 - root - INFO - got prompt
2024-11-12 16:10:54,669 - torchaudio.utils.download - INFO - The local file (E:\1-Stable-Diffusion\1-ComfyUI-Aki\.cache\torch\hub\torchaudio\models\hdemucs_high_trained.pt) exists. Skipping the download.
2024-11-12 16:10:55,425 - root - ERROR - !!! Exception during processing !!! The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.
2024-11-12 16:10:55,427 - root - ERROR - Traceback (most recent call last):
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes\src\separation.py", line 83, in main
    sources = self.separate_sources(
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes\src\separation.py", line 157, in separate_sources
    out = model.forward(chunk)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\python\lib\site-packages\torchaudio\models\_hdemucs.py", line 539, in forward
    raise ValueError(
ValueError: The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.

2024-11-12 16:10:55,427 - root - INFO - Prompt executed in 4.27 seconds
2024-11-12 16:11:00,528 - root - INFO - got prompt
2024-11-12 16:11:00,836 - torchaudio.utils.download - INFO - The local file (E:\1-Stable-Diffusion\1-ComfyUI-Aki\.cache\torch\hub\torchaudio\models\hdemucs_high_trained.pt) exists. Skipping the download.
2024-11-12 16:11:01,430 - root - ERROR - !!! Exception during processing !!! The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.
2024-11-12 16:11:01,430 - root - ERROR - Traceback (most recent call last):
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes\src\separation.py", line 83, in main
    sources = self.separate_sources(
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes\src\separation.py", line 157, in separate_sources
    out = model.forward(chunk)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\python\lib\site-packages\torchaudio\models\_hdemucs.py", line 539, in forward
    raise ValueError(
ValueError: The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.

2024-11-12 16:11:01,431 - root - INFO - Prompt executed in 0.89 seconds
2024-11-12 16:11:16,430 - root - INFO - got prompt
2024-11-12 16:11:16,731 - torchaudio.utils.download - INFO - The local file (E:\1-Stable-Diffusion\1-ComfyUI-Aki\.cache\torch\hub\torchaudio\models\hdemucs_high_trained.pt) exists. Skipping the download.
2024-11-12 16:11:17,404 - root - ERROR - !!! Exception during processing !!! The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.
2024-11-12 16:11:17,405 - root - ERROR - Traceback (most recent call last):
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes\src\separation.py", line 83, in main
    sources = self.separate_sources(
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes\src\separation.py", line 157, in separate_sources
    out = model.forward(chunk)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\python\lib\site-packages\torchaudio\models\_hdemucs.py", line 539, in forward
    raise ValueError(
ValueError: The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.

2024-11-12 16:11:17,406 - root - INFO - Prompt executed in 0.96 seconds
2024-11-12 16:12:47,293 - root - INFO - got prompt
2024-11-12 16:12:47,660 - torchaudio.utils.download - INFO - The local file (E:\1-Stable-Diffusion\1-ComfyUI-Aki\.cache\torch\hub\torchaudio\models\hdemucs_high_trained.pt) exists. Skipping the download.
2024-11-12 16:12:48,202 - root - ERROR - !!! Exception during processing !!! The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.
2024-11-12 16:12:48,202 - root - ERROR - Traceback (most recent call last):
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes\src\separation.py", line 83, in main
    sources = self.separate_sources(
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes\src\separation.py", line 157, in separate_sources
    out = model.forward(chunk)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\python\lib\site-packages\torchaudio\models\_hdemucs.py", line 539, in forward
    raise ValueError(
ValueError: The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.

2024-11-12 16:12:48,203 - root - INFO - Prompt executed in 0.91 seconds
2024-11-12 16:14:22,777 - root - INFO - got prompt
2024-11-12 16:14:23,063 - torchaudio.utils.download - INFO - The local file (E:\1-Stable-Diffusion\1-ComfyUI-Aki\.cache\torch\hub\torchaudio\models\hdemucs_high_trained.pt) exists. Skipping the download.
2024-11-12 16:14:23,747 - root - ERROR - !!! Exception during processing !!! The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.
2024-11-12 16:14:23,747 - root - ERROR - Traceback (most recent call last):
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes\src\separation.py", line 83, in main
    sources = self.separate_sources(
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\custom_nodes\ComfyUI_audio-separation-nodes\src\separation.py", line 157, in separate_sources
    out = model.forward(chunk)
  File "E:\1-Stable-Diffusion\1-ComfyUI-Aki\python\lib\site-packages\torchaudio\models\_hdemucs.py", line 539, in forward
    raise ValueError(
ValueError: The channel dimension of input Tensor must match `audio_channels` of HDemucs model. Found:1.

2024-11-12 16:14:23,748 - root - INFO - Prompt executed in 0.97 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":7,"last_link_id":3,"nodes":[{"id":1,"type":"AudioSeparation","pos":{"0":1482.5,"1":587.5},"size":{"0":315,"1":166},"flags":{},"order":2,"mode":0,"inputs":[{"name":"audio","type":"AUDIO","link":3,"label":"audio"}],"outputs":[{"name":"Bass","type":"AUDIO","links":null,"label":"Bass"},{"name":"Drums","type":"AUDIO","links":null,"label":"Drums"},{"name":"Other","type":"AUDIO","links":null,"label":"Other"},{"name":"Vocals","type":"AUDIO","links":[2],"label":"Vocals","slot_index":3}],"properties":{"Node name for S&R":"AudioSeparation"},"widgets_values":["linear",10,0.1]},{"id":3,"type":"PreviewAudio","pos":{"0":1992.7506103515625,"1":614.7694091796875},"size":{"0":315,"1":76},"flags":{},"order":3,"mode":0,"inputs":[{"name":"audio","type":"AUDIO","link":2,"label":"音频"}],"outputs":[],"properties":{"Node name for S&R":"PreviewAudio"},"widgets_values":[null]},{"id":5,"type":"LoadAudio","pos":{"0":860,"1":576},"size":{"0":315,"1":124},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"AUDIO","type":"AUDIO","links":[3],"label":"音频","slot_index":0}],"properties":{"Node name for S&R":"LoadAudio"},"widgets_values":["291c04e5db01b9d20e13eee56da15c8e.wav",null,""]},{"id":6,"type":"AudioCrop","pos":{"0":1085,"1":415},"size":{"0":315,"1":82},"flags":{},"order":1,"mode":0,"inputs":[{"name":"audio","type":"AUDIO","link":null,"label":"audio"}],"outputs":[{"name":"AUDIO","type":"AUDIO","links":null,"label":"AUDIO"}],"properties":{"Node name for S&R":"AudioCrop"},"widgets_values":["0:00","1:00"]}],"links":[[2,1,3,3,0,"AUDIO"],[3,5,0,1,0,"AUDIO"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.464100000000001,"offset":[-372.8014479885263,-194.2739054709378]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

any solution to this error?

many thanks.

**Comment by christian-byrne** [comment]
Confirmed the issue happens when using mono-channel input.

**Comment by christian-byrne** [comment]
[1caf44d](https://github.com/christian-byrne/audio-separation-nodes-comfyui/commit/1caf44dbb508066d75ae3877bd222b944c0a4d36). Was only required for separation, other utilities handle monochannel already.
