### ISSUE TITLE
ERROR MESSAGE WHEN QUEUEING PROMPT

### ISSUE THREAD

**Issue by NomadLuis** [christian-byrne/audio-separation-nodes-comfyui#9]
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 84, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by christian-byrne** [comment]
Someone had a similar issue in #5 (comments)

**Comment by christian-byrne** [comment]
This is harmless Windows asyncio noise from Python's `ProactorEventLoop` — it does not affect audio separation results and can be safely ignored.

Added a Troubleshooting section to the README documenting this. See PR #32.
